/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PearlsRouteImport } from './routes/pearls'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as MuscleRelaxantsRouteImport } from './routes/muscle-relaxants'
import { Route as MachineRouteImport } from './routes/machine'
import { Route as IntubationRouteImport } from './routes/intubation'
import { Route as InhalationalRouteImport } from './routes/inhalational'
import { Route as HemodynamicsRouteImport } from './routes/hemodynamics'
import { Route as FluidsRouteImport } from './routes/fluids'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as EmergenciesRouteImport } from './routes/emergencies'
import { Route as DrugsRouteImport } from './routes/drugs'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as AirwayAnatomyRouteImport } from './routes/airway-anatomy'
import { Route as AirwayRouteImport } from './routes/airway'
import { Route as IndexRouteImport } from './routes/index'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PearlsRoute = PearlsRouteImport.update({
  id: '/pearls',
  path: '/pearls',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const MuscleRelaxantsRoute = MuscleRelaxantsRouteImport.update({
  id: '/muscle-relaxants',
  path: '/muscle-relaxants',
  getParentRoute: () => rootRouteImport,
} as any)
const MachineRoute = MachineRouteImport.update({
  id: '/machine',
  path: '/machine',
  getParentRoute: () => rootRouteImport,
} as any)
const IntubationRoute = IntubationRouteImport.update({
  id: '/intubation',
  path: '/intubation',
  getParentRoute: () => rootRouteImport,
} as any)
const InhalationalRoute = InhalationalRouteImport.update({
  id: '/inhalational',
  path: '/inhalational',
  getParentRoute: () => rootRouteImport,
} as any)
const HemodynamicsRoute = HemodynamicsRouteImport.update({
  id: '/hemodynamics',
  path: '/hemodynamics',
  getParentRoute: () => rootRouteImport,
} as any)
const FluidsRoute = FluidsRouteImport.update({
  id: '/fluids',
  path: '/fluids',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergenciesRoute = EmergenciesRouteImport.update({
  id: '/emergencies',
  path: '/emergencies',
  getParentRoute: () => rootRouteImport,
} as any)
const DrugsRoute = DrugsRouteImport.update({
  id: '/drugs',
  path: '/drugs',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AirwayAnatomyRoute = AirwayAnatomyRouteImport.update({
  id: '/airway-anatomy',
  path: '/airway-anatomy',
  getParentRoute: () => rootRouteImport,
} as any)
const AirwayRoute = AirwayRouteImport.update({
  id: '/airway',
  path: '/airway',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/airway': typeof AirwayRoute
  '/airway-anatomy': typeof AirwayAnatomyRoute
  '/cases': typeof CasesRoute
  '/drugs': typeof DrugsRoute
  '/emergencies': typeof EmergenciesRoute
  '/favorites': typeof FavoritesRoute
  '/fluids': typeof FluidsRoute
  '/hemodynamics': typeof HemodynamicsRoute
  '/inhalational': typeof InhalationalRoute
  '/intubation': typeof IntubationRoute
  '/machine': typeof MachineRoute
  '/muscle-relaxants': typeof MuscleRelaxantsRoute
  '/notes': typeof NotesRoute
  '/pearls': typeof PearlsRoute
  '/search': typeof SearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/airway': typeof AirwayRoute
  '/airway-anatomy': typeof AirwayAnatomyRoute
  '/cases': typeof CasesRoute
  '/drugs': typeof DrugsRoute
  '/emergencies': typeof EmergenciesRoute
  '/favorites': typeof FavoritesRoute
  '/fluids': typeof FluidsRoute
  '/hemodynamics': typeof HemodynamicsRoute
  '/inhalational': typeof InhalationalRoute
  '/intubation': typeof IntubationRoute
  '/machine': typeof MachineRoute
  '/muscle-relaxants': typeof MuscleRelaxantsRoute
  '/notes': typeof NotesRoute
  '/pearls': typeof PearlsRoute
  '/search': typeof SearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/airway': typeof AirwayRoute
  '/airway-anatomy': typeof AirwayAnatomyRoute
  '/cases': typeof CasesRoute
  '/drugs': typeof DrugsRoute
  '/emergencies': typeof EmergenciesRoute
  '/favorites': typeof FavoritesRoute
  '/fluids': typeof FluidsRoute
  '/hemodynamics': typeof HemodynamicsRoute
  '/inhalational': typeof InhalationalRoute
  '/intubation': typeof IntubationRoute
  '/machine': typeof MachineRoute
  '/muscle-relaxants': typeof MuscleRelaxantsRoute
  '/notes': typeof NotesRoute
  '/pearls': typeof PearlsRoute
  '/search': typeof SearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/airway'
    | '/airway-anatomy'
    | '/cases'
    | '/drugs'
    | '/emergencies'
    | '/favorites'
    | '/fluids'
    | '/hemodynamics'
    | '/inhalational'
    | '/intubation'
    | '/machine'
    | '/muscle-relaxants'
    | '/notes'
    | '/pearls'
    | '/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/airway'
    | '/airway-anatomy'
    | '/cases'
    | '/drugs'
    | '/emergencies'
    | '/favorites'
    | '/fluids'
    | '/hemodynamics'
    | '/inhalational'
    | '/intubation'
    | '/machine'
    | '/muscle-relaxants'
    | '/notes'
    | '/pearls'
    | '/search'
  id:
    | '__root__'
    | '/'
    | '/airway'
    | '/airway-anatomy'
    | '/cases'
    | '/drugs'
    | '/emergencies'
    | '/favorites'
    | '/fluids'
    | '/hemodynamics'
    | '/inhalational'
    | '/intubation'
    | '/machine'
    | '/muscle-relaxants'
    | '/notes'
    | '/pearls'
    | '/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AirwayRoute: typeof AirwayRoute
  AirwayAnatomyRoute: typeof AirwayAnatomyRoute
  CasesRoute: typeof CasesRoute
  DrugsRoute: typeof DrugsRoute
  EmergenciesRoute: typeof EmergenciesRoute
  FavoritesRoute: typeof FavoritesRoute
  FluidsRoute: typeof FluidsRoute
  HemodynamicsRoute: typeof HemodynamicsRoute
  InhalationalRoute: typeof InhalationalRoute
  IntubationRoute: typeof IntubationRoute
  MachineRoute: typeof MachineRoute
  MuscleRelaxantsRoute: typeof MuscleRelaxantsRoute
  NotesRoute: typeof NotesRoute
  PearlsRoute: typeof PearlsRoute
  SearchRoute: typeof SearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pearls': {
      id: '/pearls'
      path: '/pearls'
      fullPath: '/pearls'
      preLoaderRoute: typeof PearlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/muscle-relaxants': {
      id: '/muscle-relaxants'
      path: '/muscle-relaxants'
      fullPath: '/muscle-relaxants'
      preLoaderRoute: typeof MuscleRelaxantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machine': {
      id: '/machine'
      path: '/machine'
      fullPath: '/machine'
      preLoaderRoute: typeof MachineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intubation': {
      id: '/intubation'
      path: '/intubation'
      fullPath: '/intubation'
      preLoaderRoute: typeof IntubationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inhalational': {
      id: '/inhalational'
      path: '/inhalational'
      fullPath: '/inhalational'
      preLoaderRoute: typeof InhalationalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hemodynamics': {
      id: '/hemodynamics'
      path: '/hemodynamics'
      fullPath: '/hemodynamics'
      preLoaderRoute: typeof HemodynamicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluids': {
      id: '/fluids'
      path: '/fluids'
      fullPath: '/fluids'
      preLoaderRoute: typeof FluidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergencies': {
      id: '/emergencies'
      path: '/emergencies'
      fullPath: '/emergencies'
      preLoaderRoute: typeof EmergenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drugs': {
      id: '/drugs'
      path: '/drugs'
      fullPath: '/drugs'
      preLoaderRoute: typeof DrugsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airway-anatomy': {
      id: '/airway-anatomy'
      path: '/airway-anatomy'
      fullPath: '/airway-anatomy'
      preLoaderRoute: typeof AirwayAnatomyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airway': {
      id: '/airway'
      path: '/airway'
      fullPath: '/airway'
      preLoaderRoute: typeof AirwayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AirwayRoute: AirwayRoute,
  AirwayAnatomyRoute: AirwayAnatomyRoute,
  CasesRoute: CasesRoute,
  DrugsRoute: DrugsRoute,
  EmergenciesRoute: EmergenciesRoute,
  FavoritesRoute: FavoritesRoute,
  FluidsRoute: FluidsRoute,
  HemodynamicsRoute: HemodynamicsRoute,
  InhalationalRoute: InhalationalRoute,
  IntubationRoute: IntubationRoute,
  MachineRoute: MachineRoute,
  MuscleRelaxantsRoute: MuscleRelaxantsRoute,
  NotesRoute: NotesRoute,
  PearlsRoute: PearlsRoute,
  SearchRoute: SearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
